// <auto-generated />
namespace E_Nursery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class e_nursery10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(e_nursery10));
        
        string IMigrationMetadata.Id
        {
            get { return "202011062132251_e_nursery10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
