// <auto-generated />
namespace E_Nursery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class e_Nursery11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(e_Nursery11));
        
        string IMigrationMetadata.Id
        {
            get { return "202011071117407_e_Nursery11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
